"""add normalized_url unique constraint

Revision ID: 36dcc01c4dd2
Revises: b37af424189f
Create Date: 2026-01-15 09:13:20.723042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dcc01c4dd2'
down_revision: Union[str, Sequence[str], None] = 'b37af424189f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('normalized_url', sa.String(), nullable=False))
    op.create_unique_constraint('uq_audit_normalized_url', 'audit_reports', ['normalized_url'])
    op.create_unique_constraint(None, 'audit_reports', ['normalized_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_reports', type_='unique')
    op.drop_constraint('uq_audit_normalized_url', 'audit_reports', type_='unique')
    op.drop_column('audit_reports', 'normalized_url')
    # ### end Alembic commands ###
